### ISSUE TITLE
Image for Raspberry Pi 4 Model B Rev 1.1

### ISSUE THREAD

**Issue by Rathorian** [crazy-max/docker-pure-ftpd#2] opened 2020-01-06 19:52 UTC
### Behaviour
Error after connection
> Error displaying directory contents '/'

#### Steps to reproduce this issue

1. Open WinSCP
2. Enter connection information
3. Then the error appears once connected

#### Expected behaviour

> Should log into user directory

#### Actual behaviour

> I have the impression that it connects to the root directory "/"

### Configuration

* Docker version (type `docker --version`) : 19.03.5
* Docker compose version if applicable (type `docker-compose --version`) : 1.25.0
* Platform (Debian 9, Ubuntu 18.04, ...) : Raspbian 10 (buster)

### docker-compose.yml
```
version: "3.7"

networks:
  backend:
    external: true

services:
  pureftpd:
    image: "crazymax/pure-ftpd"
    container_name: "pureftpd"
    restart: "unless-stopped"
    environment:
      - "TZ=Europe/Paris"
      - "AUTH_METHOD=puredb"
    ports:
      - "2100:2100"
      - "30000-30009:30000-30009"
    volumes:
      - "/home/toto/docker/pureftpd/data:/data"
      - "/home/toto/docker/pureftpd/toto:/home/toto"
    networks:
      - "backend"
```

### Docker info

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.75-v7l+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 3.826GiB
 Name: raspberry
 ID: RCFV:QF6X:OI6T:RBJ6:KHOV:OG62:PBSX:BEK4:INKY:MJBW:OMJC:VU3F
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

### Logs

```
Use PureDB authentication method
Flags
  Secure: --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite
  Additional: -d -d
  All: -d -d --bind 0.0.0.0,2100 --ipv4only --passiveportrange 30000:30009 --noanonymous --createhomedir --nochmod --syslogfacility ftp --forcepassiveip 109.XXX.XXX.XXX --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite --login puredb:/data/pureftpd.pdb
2020-01-04 12:11:33,042 INFO Included extra file "/etc/supervisord/pure-ftpd.conf" during parsing
2020-01-04 12:11:33,043 INFO Included extra file "/etc/supervisord/syslog-ng.conf" during parsing
2020-01-04 12:11:33,043 INFO Set uid to user 0 succeeded
2020-01-04 12:11:33,051 INFO supervisord started with pid 1
2020-01-04 12:11:34,068 INFO spawned: 'pure-ftpd' with pid 13
2020-01-04 12:11:34,082 INFO spawned: 'syslog-ng' with pid 14
2020-01-04 12:11:35,088 INFO success: pure-ftpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-01-04 12:11:35,089 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Jan  4 11:14:09 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [INFO] New connection from 192.168.1.122
Jan  4 11:14:09 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
Jan  4 11:14:09 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] 220-You are user number 1 of 5 allowed.
Jan  4 11:14:09 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] 220-Local time is now 12:14. Server port: 2100.
Jan  4 11:14:09 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] 220-This is a private system - No anonymous login
Jan  4 11:14:09 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] 220 You will be disconnected after 15 minutes of inactivity.
Jan  4 11:14:09 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] Command [user] [toto]
Jan  4 11:14:09 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] 331 User toto OK. Password required
Jan  4 11:14:16 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] Command [pass] [<*>]
Jan  4 11:14:17 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [INFO] toto is now logged in
Jan  4 11:14:17 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] 230 OK. Current directory is /
Jan  4 11:14:17 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] Command [syst] []
Jan  4 11:14:17 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] 215 UNIX Type: L8
Jan  4 11:14:17 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] Command [feat] []
Jan  4 11:14:17 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] 211-Extensions supported:
 UTF8
 EPRT
 IDLE
 MDTM
 SIZE
 MFMT
 REST STREAM
 MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;
 MLSD
 PRET
 AUTH TLS
 PBSZ
 PROT
 TVFS
 ESTA
 PASV
 EPSV
 SPSV
Jan  4 11:14:17 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] 211 End.
Jan  4 11:14:17 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] Command [opts] [UTF8 ON]
Jan  4 11:14:17 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] 504 Unknown command
Jan  4 11:14:17 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] Command [pwd] []
Jan  4 11:14:17 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] 257 "/" is your current location
Jan  4 11:14:17 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] Command [type] [A]
Jan  4 11:14:17 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] 200 TYPE is now ASCII
Jan  4 11:14:17 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] Command [pasv] []
Jan  4 11:14:17 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] 227 Entering Passive Mode (109,XXX,XXX,XXX,117,57)
Jan  4 11:14:17 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] Command [mlsd] []
2020-01-04 12:20:37,891 WARN received SIGTERM indicating exit request
2020-01-04 12:20:37,892 INFO waiting for pure-ftpd, syslog-ng to die
**
ERROR:lib/window-size-counter.c:76:window_size_counter_sub: assertion failed: (old_value >= value)
Bail out! ERROR:lib/window-size-counter.c:76:window_size_counter_sub: assertion failed: (old_value >= value)
2020-01-04 12:20:39,009 INFO stopped: syslog-ng (terminated by SIGABRT (core dumped))
2020-01-04 12:20:40,014 INFO stopped: pure-ftpd (exit status 0)
Use PureDB authentication method
Flags
  Secure: --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite
  Additional: -d -d
  All: -d -d --bind 0.0.0.0,2100 --ipv4only --passiveportrange 30000:30009 --noanonymous --createhomedir --nochmod --syslogfacility ftp --forcepassiveip 109.XXX.XXX.XXX --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite --login puredb:/data/pureftpd.pdb
2020-01-04 12:21:03,622 INFO Included extra file "/etc/supervisord/pure-ftpd.conf" during parsing
2020-01-04 12:21:03,623 INFO Included extra file "/etc/supervisord/syslog-ng.conf" during parsing
2020-01-04 12:21:03,623 INFO Set uid to user 0 succeeded
2020-01-04 12:21:03,637 INFO supervisord started with pid 1
2020-01-04 12:21:04,654 INFO spawned: 'pure-ftpd' with pid 13
2020-01-04 12:21:04,668 INFO spawned: 'syslog-ng' with pid 14
2020-01-04 12:21:05,673 INFO success: pure-ftpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-01-04 12:21:05,674 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Jan  6 19:25:11 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [INFO] New connection from 192.168.1.122
Jan  6 19:25:11 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
Jan  6 19:25:11 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] 220-You are user number 1 of 5 allowed.
Jan  6 19:25:11 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] 220-Local time is now 20:25. Server port: 2100.
Jan  6 19:25:11 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] 220-This is a private system - No anonymous login
Jan  6 19:25:11 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] 220 You will be disconnected after 15 minutes of inactivity.
Jan  6 19:25:11 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] Command [user] [toto]
Jan  6 19:25:11 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] 331 User toto OK. Password required
Jan  6 19:25:50 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] Command [pass] [<*>]
Jan  6 19:25:55 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] 530 Login authentication failed
Jan  6 19:25:55 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [WARNING] Authentication failed for user [toto]
Jan  6 19:25:55 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [INFO] Logout.
Jan  6 19:25:55 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] 530 Logout.
2020-01-06 20:25:56,548 INFO reaped unknown pid 17
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [INFO] New connection from 192.168.1.122
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] 220-You are user number 1 of 5 allowed.
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] 220-Local time is now 20:26. Server port: 2100.
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] 220-This is a private system - No anonymous login
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] 220 You will be disconnected after 15 minutes of inactivity.
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] Command [user] [toto]
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] 331 User toto OK. Password required
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [DEBUG] Command [pass] [<*>]
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (?@192.168.1.122) [INFO] toto is now logged in
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] 230 OK. Current directory is /
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] Command [syst] []
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] 215 UNIX Type: L8
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] Command [feat] []
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] 211-Extensions supported:
 UTF8
 EPRT
 IDLE
 MDTM
 SIZE
 MFMT
 REST STREAM
 MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;
 MLSD
 PRET
 AUTH TLS
 PBSZ
 PROT
 TVFS
 ESTA
 PASV
 EPSV
 SPSV
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] 211 End.
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] Command [opts] [UTF8 ON]
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] 504 Unknown command
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] Command [pwd] []
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] 257 "/" is your current location
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] Command [type] [A]
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] 200 TYPE is now ASCII
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] Command [pasv] []
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] 227 Entering Passive Mode (109,XXX,XXX,XXX,117,50)
Jan  6 19:26:04 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [DEBUG] Command [mlsd] []
Jan  6 19:41:04 f812ef1dd8ea pure-ftpd: (toto@192.168.1.122) [INFO] Timeout
2020-01-06 20:41:05,594 INFO reaped unknown pid 20
```

**Comment by crazy-max** [comment] 2020-01-06 21:35
@Rathorian I cannot reproduce your issue on a Raspberry 4 . Here is my setup.

```
$ uname -a
Linux rasp4 4.19.86-v7l+ #1283 SMP Fri Nov 29 18:37:40 GMT 2019 armv7l GNU/Linux
```

```
$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 9
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.86-v7l+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 3.814GiB
 Name: rasp4
 ID: X6MM:46DE:EDKE:WP2S:VORU:FZEX:NGG3:7NIQ:RBRY:DWVW:WEZB:5FS2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

```
$ docker-compose version
docker-compose version 1.24.1, build 4667896
docker-py version: 3.7.3
CPython version: 2.7.16
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

```
$ ls -al
drwxr-xr-x 4 root root 4096 janv.  6 22:19 .
drwxr-xr-x 3 root root 4096 janv.  6 22:17 ..
drwxr-xr-x 2 root root 4096 janv.  6 22:21 data
-rw-r--r-- 1 root root  318 janv.  6 22:19 docker-compose.yml
drwxr-xr-x 3 1003 1005 4096 janv.  6 22:24 files
```

```
$ cat docker-compose.yml
version: "3.2"

services:
  pureftpd:
    image: crazymax/pure-ftpd
    container_name: pureftpd
    ports:
      - "2100:2100"
      - "30000-30009:30000-30009"
    volumes:
      - "./data:/data"
      - "./files:/home/foo"
    environment:
      - "TZ=Europe/Paris"
      - "AUTH_METHOD=puredb"
    restart: always
```

```
$ cat data/pureftpd.flags
-d
-d
```

```
$ docker-compose up -d && docker-compose logs -f
Attaching to pureftpd
pureftpd    | Use PureDB authentication method
pureftpd    | Flags
pureftpd    |   Secure: --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite
pureftpd    |   Additional: -d -d
pureftpd    |   All: -d -d --bind 0.0.0.0,2100 --ipv4only --passiveportrange 30000:30009 --noanonymous --createhomedir --nochmod --syslogfacility ftp --forcepassiveip xxx.xxx.xxx.xxx --maxclientsnumber 5 --maxclientsperip 5 --antiwarez --customerproof --dontresolve --norename --prohibitdotfilesread --prohibitdotfileswrite --login puredb:/data/pureftpd.pdb
pureftpd    | 2020-01-06 22:20:47,978 INFO Included extra file "/etc/supervisord/pure-ftpd.conf" during parsing
pureftpd    | 2020-01-06 22:20:47,979 INFO Included extra file "/etc/supervisord/syslog-ng.conf" during parsing
pureftpd    | 2020-01-06 22:20:47,979 INFO Set uid to user 0 succeeded
pureftpd    | 2020-01-06 22:20:47,987 INFO supervisord started with pid 1
pureftpd    | 2020-01-06 22:20:49,002 INFO spawned: 'pure-ftpd' with pid 13
pureftpd    | 2020-01-06 22:20:49,013 INFO spawned: 'syslog-ng' with pid 14
pureftpd    | 2020-01-06 22:20:50,018 INFO success: pure-ftpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
pureftpd    | 2020-01-06 22:20:50,018 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

```
$ docker-compose exec pureftpd pure-pw useradd foo -u 1003 -g 1005 -d /home/foo -m
```

Connect to `xxx.xxx.xxx.xxx:2100` as user `foo` and add some files, everything is ok:

![image](https://user-images.githubusercontent.com/1951866/71850276-3d6d6180-30d4-11ea-8b85-0cac461c88d7.png)

Content on server:

```
$ ls -al files/
total 32
drwxr-xr-x 3 1003 1005 4096 janv.  6 22:24 .
drwxr-xr-x 4 root root 4096 janv.  6 22:19 ..
-rw-r--r-- 1 1003 1005  624 déc.  28 16:35 CHANGELOG.md
-rw-r--r-- 1 1003 1005 2636 déc.  28 17:00 Dockerfile
-rw-r--r-- 1 1003 1005 2695 déc.  28 17:00 Dockerfile-1.0.47
-rw-r--r-- 1 1003 1005 4609 déc.  28 17:06 entrypoint.sh
drwxr-xr-x 2 1003 1005 4096 janv.  6 22:23 foo
```

So I think this is a permission issue on your side with your `toto` user on `/home/toto/docker/pureftpd/toto`. You can find help on https://github.com/jedisct1/pure-ftpd or StackOverflow.

**Comment by Rathorian** [comment] 2020-01-09 12:48
Thank you for your feedback.

Unfortunately, I could not try other changes because I have been away for a while.

Upon my return, I will try to check permissions and the like.

**Comment by crazy-max** [comment] 2020-01-14 04:25
Ok I close this issue for now, keep me in otuch.

**Closed by crazy-max** 2020-01-14 04:25 UTC
